global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "machten-api"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["machten-api:8080"]
        labels:
          app: "machten"
          environment: "development"
